name: Full-STACK SPACE Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CI: true

    strategy: 
     matrix:
     node-version:[22.x,24.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Check versions
        run: |
          node --version
          pnpm --version
      - name: Install dependencies
        run: pnpm run setup

      - name: Run tests
        run: pnpm test

      - name: Build client
        run: pnpm --dir client run build
